language: rust
sudo: required
dist: trusty
services:
  - docker
before_install:
  - docker pull ubuntu
  - docker run ubuntu:16.04 /bin/bash "apt-get update && apt-get install liblvm2-dev pkg-config make clang"
  - docker ps -a
rust:
  - stable
  - beta
matrix:
  allow_failures:
    - rust: beta
  fast_finish: true
cache: cargo
script:
  - cargo build --verbose --all
