sudo: false

addons:
  apt:
    packages:
      - liblvm2-dev

dist: xenial

notifications:
  email:
    on_success: never

language: rust

rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
  - rust: nightly
  - rust: beta
  fast_finish: true

cache:
  cargo: true

script:
  - cargo build --verbose --all
  - cargo test